name: Build & Push GIMS (prod)

on:
  push:
    branches: [ "main" ]
  tags:
    - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push frontend (latest)
        if: github.ref_type == 'branch'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/frontend.Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/gims-frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build & push backend (latest)
        if: github.ref_type == 'branch'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/backend.Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/gims-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build & push frontend (version tag)
        if: github.ref_type == 'tag'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/frontend.Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/gims-frontend:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build & push backend (version tag)
        if: github.ref_type == 'tag'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/backend.Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/gims-backend:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
